### PR TITLE
Update lscript

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Removed Mdk3-master duplicate
- Fixed broken git link

### CODE REVIEW

**Comment by arismelachroinos** [comment]
Hi , Thank you a lot for your time. However i have already fixed both issues but i am just finishing other things to upload it soon. Please if you find any other errors report it on the issues tab. Sorry for your time.

**Comment by Ekultek** [comment]
Why don’t you accept pull requests?

**Comment by arismelachroinos** [comment]
on the specific pull request I just said that I have already fixed these issues. generally, that's not the way I like it, that's why I say repeatedly to add any issues or requests on the issues tab, because I want to try and find them my own.

**Comment by thehappydinoa** [comment]
@arismelachroinos do you think you could make a Dev branch to show what you are working on so people know whats going on?

**Comment by arismelachroinos** [comment]
I see your point, I don't really know how to do that, and usually a new version doesn't take that long, this month I save too many lessons and my free time is too tight. And I had made a list of little details that I needed to fix, and it is almost done.

**Comment by thehappydinoa** [comment]
That would be great because I would love to help improve this project

**Pull request closed without merging**
