### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by roya0045**
Greetings,

I made some small tweaks, in the install.sh I force the condition check on the first item provided rather than the full string just to be safe.

Secondly I added a mass-install/all-except option to the l file as a lazy option to install everything other than some selected packages. The changes should work fine but a test might be good as I only tested the bash conditions on a bash emulator for now. (Too lazy to boot my other OS.)

I'll soon look into adding more tools but I still need to familiarize myself with bash and your code beforehand.

Tell me what you think.

P.S.: Out of curiosity, why was sniper edited out?

### CODE REVIEW

**Comment by arismelachroinos** [comment]
Hi sir, 
what do you mean that the sniper was edited out ? Its in TOOLS -> Information gathering.
Can i kindly ask to just make new issues and request tools to be added? I work on this project every day and when a new version is done, i upload the whole thing. Also , as for the mass installation , thats how it was at the beggining and it wasnt any good. Thats due to two reasons. First thats a lot of tools and rearly one would use even more than half of them . And second is that it was far too slow. It took almost 1 hour to install everything , and you needed to be there to press 'y' and select install options for some scripts. You cant just leave it and install everything. the exception thing is good idea , but not a must for now at least.

Thanks a lot for your time.

**Comment by roya0045** [comment]
My bad sniper is in the l file,  as for my modification I'll need to tweak something, the wildcard thing doesn't seem to totally work, I'll find an alternative.

**Comment by arismelachroinos** [comment]
No problem. My advice is to start making a new script from scratch, I unfortunately cant merge this because i work a bit different.

**Comment by roya0045** [comment]
All good!

**Pull request closed without merging**
